module.exports = {
  apps: [
    {
      name: 'resto-nodeserver',
      cwd: './server',
      script: 'app.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
        PORT: 2000,
        // RestoAnalytics public URL (업장별 비교 → Multi-Branch Board)
        RESTO_ANALYTICS_PUBLIC_URL: 'http://45.32.119.62:2998',
        // Avoid inherited IDE/sandbox proxy breaking Loyverse HTTPS calls.
        HTTP_PROXY: '',
        HTTPS_PROXY: '',
        http_proxy: '',
        https_proxy: '',
        ALL_PROXY: '',
        all_proxy: '',
        GIT_HTTP_PROXY: '',
        GIT_HTTPS_PROXY: '',
        SOCKS_PROXY: '',
        SOCKS5_PROXY: '',
        socks_proxy: '',
        socks5_proxy: '',
        NO_PROXY: '127.0.0.1,::1,localhost',
        no_proxy: '127.0.0.1,::1,localhost',
      },
    },
    {
      name: 'resto-frontend',
      cwd: '.',
      script: 'npm',
      args: 'run dev',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
        PORT: 3000,
      },
    },
    {
      name: 'resto-pyserver',
      cwd: './pyserver',
      script: './.venv/bin/python',
      args: '-m uvicorn main:app --host 0.0.0.0 --port 2100 --no-access-log',
      instances: 1,
      exec_mode: 'fork',
      env: {
        PYTHONUNBUFFERED: '1',
        PORT: 2100,
        HTTP_PROXY: '',
        HTTPS_PROXY: '',
        http_proxy: '',
        https_proxy: '',
        ALL_PROXY: '',
        all_proxy: '',
        GIT_HTTP_PROXY: '',
        GIT_HTTPS_PROXY: '',
        SOCKS_PROXY: '',
        SOCKS5_PROXY: '',
        socks_proxy: '',
        socks5_proxy: '',
        NO_PROXY: '127.0.0.1,::1,localhost',
        no_proxy: '127.0.0.1,::1,localhost',
      },
    },
  ],
};
